[versions]
kotlin = "1.9.21"
kotlinx-serialization = "1.6.2"
ksp = "1.9.21-1.0.15"
ktfmt = "0.46"
jvmTarget = "17"
moshix = "0.25.1"
moshi = "1.15.0"
tikxml = "0.8.15"
xmlutil = "0.86.2"

[plugins]
detekt = { id = "io.gitlab.arturbosch.detekt", version = "1.23.4" }
dokka = { id = "org.jetbrains.dokka", version = "1.9.10" }
lint = { id = "com.android.lint", version = "8.1.2" }
mavenPublish = { id = "com.vanniktech.maven.publish", version = "0.25.3" }
moshix = { id = "dev.zacsweers.moshix", version.ref = "moshix" }
kotlin-jvm = { id = "org.jetbrains.kotlin.jvm", version.ref = "kotlin" }
kotlin-serialization = { id = "org.jetbrains.kotlin.plugin.serialization", version.ref = "kotlin" }
ksp = { id = "com.google.devtools.ksp", version.ref = "ksp" }
spotless = { id = "com.diffplug.spotless", version = "6.23.3" }
binaryCompatibilityValidator = { id = "org.jetbrains.kotlinx.binary-compatibility-validator", version = "0.13.2" }
retry = { id = "org.gradle.test-retry", version = "1.5.8" }

[libraries]
autoService-annotations = "com.google.auto.service:auto-service-annotations:1.1.1"
autoService-ksp = "dev.zacsweers.autoservice:auto-service-ksp:1.1.0"
bugsnag = "com.bugsnag:bugsnag:3.7.1"
clikt = "com.github.ajalt.clikt:clikt:4.2.1"
kotlinShell = "eu.jrie.jetbrains:kotlin-shell-core:0.2.1"
kotlin-reflect = { module = "org.jetbrains.kotlin:kotlin-reflect", version.ref = "kotlin" }
kotlinx-serialization-core = { module = "org.jetbrains.kotlinx:kotlinx-serialization-core", version.ref = "kotlinx-serialization" }
moshi = { module = "com.squareup.moshi:moshi", version.ref = "moshi" }
okhttp = "com.squareup.okhttp3:okhttp:4.12.0"
okio = "com.squareup.okio:okio:3.7.0"
sarif4k = "io.github.detekt.sarif4k:sarif4k:0.5.0"
slf4jNop = "org.slf4j:slf4j-nop:2.0.9"
junit = "junit:junit:4.13.2"
tikxml-htmlEscape = { module = "com.tickaroo.tikxml:converter-htmlescape", version.ref = "tikxml" }
truth = "com.google.truth:truth:1.1.5"
xmlutil-core = { module = "io.github.pdvrieze.xmlutil:core", version.ref = "xmlutil" }
xmlutil-serialization = { module = "io.github.pdvrieze.xmlutil:serialization", version.ref = "xmlutil" }