[versions]
kotlin = "1.6.10"
ktlint = "0.44.0"
jvmTarget = "1.8"

[plugins]
detekt = { id = "io.gitlab.arturbosch.detekt", version = "1.19.0" }
dokka = { id = "org.jetbrains.dokka", version = "1.6.10" }
lint = { id = "com.android.lint", version = "7.1.2" }
mavenPublish = { id = "com.vanniktech.maven.publish", version = "0.19.0" }
spotless = { id = "com.diffplug.spotless", version = "6.3.0" }

[libraries]
clikt = "com.github.ajalt.clikt:clikt:3.4.0"
junit = "junit:junit:4.13.2"
