name: CI

on:
  # Only run push on main
  push:
    branches:
      - main
    paths-ignore:
      - 'docs/**'
      - '*.md'
  # Always run on PRs
  pull_request:
  merge_group:

concurrency:
  group: 'ci-${{ github.event.merge_group.head_ref || github.head_ref }}-${{ github.workflow }}'
  cancel-in-progress: true

jobs:
  build:
    # Necessary for ResultProcessorTest.testExecuteCommandWithStderr
    runs-on: 'macos-14'
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Gradle Wrapper Validation
        uses: gradle/actions/wrapper-validation@v3

      - name: Install JDK
        uses: actions/setup-java@v4
        with:
          distribution: 'zulu'
          java-version: '21'

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v3

      - name: Build and test
        run: ./gradlew check --quiet

      - name: (Fail-only) Upload build reports
        if: failure()
        uses: actions/upload-artifact@v4
        with:
          name: reports
          path: |
            **/build/reports/**

      - name: Upload snapshot (main only)
        env:
          ORG_GRADLE_PROJECT_mavenCentralUsername: ${{ secrets.SonatypeUsername }}
          ORG_GRADLE_PROJECT_mavenCentralPassword: ${{ secrets.SonatypePassword }}
        run: |
          ./gradlew publish
        if: success() && github.ref == 'refs/heads/main' && github.event_name != 'pull_request'
